// Package generator emits Go source for converted ModGadget bitmap fonts.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"strconv"

	"github.com/rdon-key/modgadget-fonts/internal/bdf"
)

const bitmapChunkSize = 32

// Options controls the package and variable names in generated code.
type Options struct {
	PackageName  string
	VariableName string
}

// Generate returns gofmt-formatted Go source for src.
func Generate(src bdf.ConvertedFont, options Options) ([]byte, error) {
	if err := validateIdentifier("PackageName", options.PackageName); err != nil {
		return nil, err
	}
	if err := validateIdentifier("VariableName", options.VariableName); err != nil {
		return nil, err
	}
	if err := validateConvertedFont(src); err != nil {
		return nil, err
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by modgadget-fonts. DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "package %s\n\n", options.PackageName)
	fmt.Fprintln(&output, `import fontpkg "github.com/rdon-key/modgadget-fonts/font"`)
	fmt.Fprintln(&output)
	fmt.Fprintf(&output, "var %s = fontpkg.New(\n", options.VariableName)
	fmt.Fprintln(&output, "fontpkg.Metrics{")
	fmt.Fprintf(&output, "Ascent: %d,\n", src.Metrics.Ascent)
	fmt.Fprintf(&output, "Descent: %d,\n", src.Metrics.Descent)
	fmt.Fprintln(&output, "},")
	fmt.Fprintln(&output, "[]fontpkg.GlyphInfo{")
	for _, glyph := range src.Glyphs {
		fmt.Fprintln(&output, "{")
		fmt.Fprintf(&output, "Rune: %s,\n", strconv.QuoteRuneToASCII(glyph.Rune))
		fmt.Fprintf(&output, "BitmapOffset: %d,\n", glyph.BitmapOffset)
		fmt.Fprintf(&output, "Width: %d,\n", glyph.Width)
		fmt.Fprintf(&output, "Height: %d,\n", glyph.Height)
		fmt.Fprintf(&output, "XOffset: %d,\n", glyph.XOffset)
		fmt.Fprintf(&output, "YOffset: %d,\n", glyph.YOffset)
		fmt.Fprintf(&output, "Advance: %d,\n", glyph.Advance)
		fmt.Fprintln(&output, "},")
	}
	fmt.Fprintln(&output, "},")
	writeBitmapExpression(&output, src.Bitmap)
	fmt.Fprintln(&output, ",")
	fmt.Fprintln(&output, ")")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func validateIdentifier(field, value string) error {
	if value == "" {
		return fmt.Errorf("%s must not be empty", field)
	}
	if value == "_" || !token.IsIdentifier(value) {
		return fmt.Errorf("%s %q is not a valid Go identifier", field, value)
	}
	return nil
}

func validateConvertedFont(src bdf.ConvertedFont) error {
	if len(src.Glyphs) == 0 {
		if len(src.Bitmap) != 0 {
			return fmt.Errorf("glyph index 0: bitmap contains %d bytes but there are no glyphs", len(src.Bitmap))
		}
		return nil
	}

	var expectedOffset uint64
	for i, glyph := range src.Glyphs {
		encoding := int64(glyph.Rune)
		if encoding < 0 || encoding > 0x10ffff {
			return fmt.Errorf("glyph index %d: rune is outside the Unicode range", i)
		}
		if encoding >= 0xd800 && encoding <= 0xdfff {
			return fmt.Errorf("glyph index %d U+%04X: rune is a Unicode surrogate", i, glyph.Rune)
		}
		if i > 0 {
			previous := src.Glyphs[i-1].Rune
			if glyph.Rune == previous {
				return fmt.Errorf("glyph index %d U+%04X: duplicate rune", i, glyph.Rune)
			}
			if glyph.Rune < previous {
				return fmt.Errorf("glyph index %d U+%04X: glyphs are not in ascending rune order", i, glyph.Rune)
			}
		}
		if glyph.Width < 0 || glyph.Height < 0 {
			return fmt.Errorf("glyph index %d U+%04X: width and height must not be negative", i, glyph.Rune)
		}

		actualOffset := uint64(glyph.BitmapOffset)
		if actualOffset != expectedOffset {
			return fmt.Errorf("glyph index %d U+%04X: BitmapOffset is %d; expected %d",
				i, glyph.Rune, actualOffset, expectedOffset)
		}
		rowBytes := (uint64(glyph.Width) + 7) / 8
		length := rowBytes * uint64(glyph.Height)
		if length > uint64(^uint32(0))-expectedOffset {
			return fmt.Errorf("glyph index %d U+%04X: bitmap end exceeds uint32", i, glyph.Rune)
		}
		expectedOffset += length
		if expectedOffset > uint64(len(src.Bitmap)) {
			return fmt.Errorf("glyph index %d U+%04X: bitmap ends at %d but data has %d bytes",
				i, glyph.Rune, expectedOffset, len(src.Bitmap))
		}
	}

	if expectedOffset != uint64(len(src.Bitmap)) {
		return fmt.Errorf("glyph index %d: bitmap has %d trailing unused bytes",
			len(src.Glyphs)-1, uint64(len(src.Bitmap))-expectedOffset)
	}
	return nil
}

func writeBitmapExpression(output *bytes.Buffer, bitmap string) {
	if bitmap == "" {
		output.WriteString(`""`)
		return
	}
	for start := 0; start < len(bitmap); start += bitmapChunkSize {
		end := start + bitmapChunkSize
		if end > len(bitmap) {
			end = len(bitmap)
		}
		if start > 0 {
			output.WriteString(" +\n")
		}
		output.WriteString(strconv.QuoteToASCII(bitmap[start:end]))
	}
}
