package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"reflect"
	"strconv"
	"strings"
	"testing"

	"github.com/rdon-key/modgadget-fonts/font"
	"github.com/rdon-key/modgadget-fonts/internal/bdf"
)

var testOptions = Options{PackageName: "generated", VariableName: "Example"}

func representativeFont() bdf.ConvertedFont {
	return bdf.ConvertedFont{
		Metrics: font.Metrics{Ascent: 10, Descent: 3},
		Glyphs: []font.GlyphInfo{
			{
				Rune: 'A', BitmapOffset: 0, Width: 8, Height: 1,
				XOffset: -1, YOffset: 2, Advance: 9,
			},
			{Rune: '\u0301', BitmapOffset: 1},
			{Rune: '\u4e2d', BitmapOffset: 1, Width: 8, Height: 1, YOffset: 10, Advance: 8},
			{Rune: '\ufe0f', BitmapOffset: 2},
		},
		Bitmap: "\x81\xff",
	}
}

func TestGenerateSourceStructureAndFields(t *testing.T) {
	src := representativeFont()
	got, err := Generate(src, testOptions)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "generated.go", got, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v\n%s", err, got)
	}
	if !bytes.HasSuffix(got, []byte("\n")) {
		t.Error("generated source does not end in a newline")
	}

	source := string(got)
	checks := []string{
		"// Code generated by modgadget-fonts. DO NOT EDIT.",
		"package generated",
		`fontpkg "github.com/rdon-key/modgadget-fonts/font"`,
		"var Example = fontpkg.New(",
		"Ascent:", "10", "Descent:", "3",
		"Rune:", "'A'", `\u0301`, `\u4e2d`, `\ufe0f`,
		"BitmapOffset:", "Width:", "Height:", "XOffset:", "YOffset:", "Advance:",
	}
	for _, check := range checks {
		if !strings.Contains(source, check) {
			t.Errorf("generated source does not contain %q\n%s", check, source)
		}
	}
	compact := strings.NewReplacer(" ", "", "\t", "", "\r", "", "\n", "").Replace(source)
	for _, check := range []string{
		"Ascent:10,", "Descent:3,", "Rune:'A',", "BitmapOffset:0,",
		"Width:8,", "Height:1,", "XOffset:-1,", "YOffset:2,", "Advance:9,",
	} {
		if !strings.Contains(compact, check) {
			t.Errorf("generated source does not contain field value %q\n%s", check, source)
		}
	}
}

func TestGeneratePackageNamedFontUsesAlias(t *testing.T) {
	generated, err := Generate(bdf.ConvertedFont{}, Options{PackageName: "font", VariableName: "Empty"})
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	if !strings.Contains(string(generated), "package font") ||
		!strings.Contains(string(generated), `import fontpkg "github.com/rdon-key/modgadget-fonts/font"`) {
		t.Fatalf("generated source does not use the required alias:\n%s", generated)
	}
}

func TestGenerateRuneLiteralsAreASCIIAndParseable(t *testing.T) {
	src := bdf.ConvertedFont{Glyphs: []font.GlyphInfo{
		{Rune: '\n'},
		{Rune: 'A'},
		{Rune: '\u0301'},
		{Rune: '\u4e2d'},
		{Rune: '\ufe0f'},
	}}
	got, err := Generate(src, testOptions)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "runes.go", got, parser.AllErrors); err != nil {
		t.Fatalf("generated source does not parse: %v", err)
	}
	for _, expected := range []string{`'\n'`, `'A'`, `'\u0301'`, `'\u4e2d'`, `'\ufe0f'`} {
		if !strings.Contains(string(got), expected) {
			t.Errorf("generated source does not contain rune literal %s", expected)
		}
	}
	for _, b := range got {
		if b >= 0x80 {
			t.Fatalf("generated rune source contains non-ASCII byte %#x", b)
		}
	}
}

func TestGenerateBitmapRoundTripAndChunks(t *testing.T) {
	bitmap := make([]byte, 70)
	for i := range bitmap {
		bitmap[i] = byte(i)
	}
	copy(bitmap, []byte{0x00, 0xff, '"', '\\', '\n', 0x80, 0xfe})
	bitmap[31] = 0xff
	bitmap[32] = 0x00
	bitmap[63] = '\\'
	bitmap[64] = '"'
	src := bdf.ConvertedFont{
		Glyphs: []font.GlyphInfo{{Rune: 'A', Width: 8, Height: int16(len(bitmap))}},
		Bitmap: string(bitmap),
	}

	generated, err := Generate(src, testOptions)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	restored, literalCount, err := restoreBitmap(generated)
	if err != nil {
		t.Fatalf("restore generated bitmap: %v", err)
	}
	if restored != src.Bitmap {
		t.Fatalf("restored bitmap differs:\ngot:  %x\nwant: %x", restored, src.Bitmap)
	}
	if literalCount != 3 {
		t.Errorf("bitmap literal count = %d, want 3 for 70 bytes", literalCount)
	}
}

func TestGenerateEmptyBitmapAndNoGlyphs(t *testing.T) {
	generated, err := Generate(bdf.ConvertedFont{}, testOptions)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	restored, count, err := restoreBitmap(generated)
	if err != nil {
		t.Fatal(err)
	}
	if restored != "" || count != 1 {
		t.Errorf("empty bitmap restored as %q from %d literals", restored, count)
	}
}

func TestGenerateDeterministicAndDoesNotModifyInput(t *testing.T) {
	src := representativeFont()
	beforeGlyphs := append([]font.GlyphInfo(nil), src.Glyphs...)
	beforeBitmap := src.Bitmap

	first, err := Generate(src, testOptions)
	if err != nil {
		t.Fatalf("first Generate() error: %v", err)
	}
	second, err := Generate(src, testOptions)
	if err != nil {
		t.Fatalf("second Generate() error: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("Generate returned different bytes for identical input")
	}
	if !reflect.DeepEqual(src.Glyphs, beforeGlyphs) || src.Bitmap != beforeBitmap {
		t.Fatal("Generate modified its input")
	}
}

func TestGenerateIdentifierErrors(t *testing.T) {
	tests := []struct {
		name    string
		options Options
		field   string
	}{
		{name: "empty package", options: Options{VariableName: "Font"}, field: "PackageName"},
		{name: "invalid package", options: Options{PackageName: "bad-name", VariableName: "Font"}, field: "PackageName"},
		{name: "package keyword", options: Options{PackageName: "package", VariableName: "Font"}, field: "PackageName"},
		{name: "package blank identifier", options: Options{PackageName: "_", VariableName: "Font"}, field: "PackageName"},
		{name: "empty variable", options: Options{PackageName: "font"}, field: "VariableName"},
		{name: "invalid variable", options: Options{PackageName: "font", VariableName: "bad-name"}, field: "VariableName"},
		{name: "variable keyword", options: Options{PackageName: "font", VariableName: "var"}, field: "VariableName"},
		{name: "variable blank identifier", options: Options{PackageName: "font", VariableName: "_"}, field: "VariableName"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := Generate(bdf.ConvertedFont{}, test.options)
			if err == nil || !strings.Contains(err.Error(), test.field) {
				t.Fatalf("Generate() error = %v, want %s error", err, test.field)
			}
		})
	}
}

func TestGenerateConvertedFontErrors(t *testing.T) {
	tests := []struct {
		name   string
		src    bdf.ConvertedFont
		needle string
	}{
		{
			name: "glyph order",
			src: bdf.ConvertedFont{Glyphs: []font.GlyphInfo{
				{Rune: 'B'}, {Rune: 'A'},
			}},
			needle: "ascending rune order",
		},
		{
			name: "duplicate rune",
			src: bdf.ConvertedFont{Glyphs: []font.GlyphInfo{
				{Rune: 'A'}, {Rune: 'A'},
			}},
			needle: "duplicate rune",
		},
		{
			name:   "Unicode range",
			src:    bdf.ConvertedFont{Glyphs: []font.GlyphInfo{{Rune: rune(0x110000)}}},
			needle: "Unicode range",
		},
		{
			name:   "surrogate",
			src:    bdf.ConvertedFont{Glyphs: []font.GlyphInfo{{Rune: rune(0xd800)}}},
			needle: "Unicode surrogate",
		},
		{
			name:   "negative width",
			src:    bdf.ConvertedFont{Glyphs: []font.GlyphInfo{{Rune: 'A', Width: -1}}},
			needle: "must not be negative",
		},
		{
			name:   "negative height",
			src:    bdf.ConvertedFont{Glyphs: []font.GlyphInfo{{Rune: 'A', Height: -1}}},
			needle: "must not be negative",
		},
		{
			name:   "first offset",
			src:    bdf.ConvertedFont{Glyphs: []font.GlyphInfo{{Rune: 'A', BitmapOffset: 1}}},
			needle: "expected 0",
		},
		{
			name: "offset gap",
			src: bdf.ConvertedFont{
				Glyphs: []font.GlyphInfo{
					{Rune: 'A', Width: 8, Height: 1},
					{Rune: 'B', BitmapOffset: 2, Width: 8, Height: 1},
				},
				Bitmap: "\x00\x00\x00",
			},
			needle: "expected 1",
		},
		{
			name: "offset backward",
			src: bdf.ConvertedFont{
				Glyphs: []font.GlyphInfo{
					{Rune: 'A', Width: 8, Height: 1},
					{Rune: 'B', BitmapOffset: 0, Width: 8, Height: 1},
				},
				Bitmap: "\x00\x00",
			},
			needle: "expected 1",
		},
		{
			name: "bitmap short",
			src: bdf.ConvertedFont{
				Glyphs: []font.GlyphInfo{{Rune: 'A', Width: 8, Height: 2}},
				Bitmap: "\x00",
			},
			needle: "bitmap ends at 2",
		},
		{
			name: "bitmap trailing data",
			src: bdf.ConvertedFont{
				Glyphs: []font.GlyphInfo{{Rune: 'A', Width: 8, Height: 1}},
				Bitmap: "\x00\xff",
			},
			needle: "trailing unused",
		},
		{
			name:   "bitmap without glyphs",
			src:    bdf.ConvertedFont{Bitmap: "\x00"},
			needle: "no glyphs",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := Generate(test.src, testOptions)
			if err == nil || !strings.Contains(err.Error(), test.needle) {
				t.Fatalf("Generate() error = %v, want substring %q", err, test.needle)
			}
		})
	}
}

func restoreBitmap(source []byte) (string, int, error) {
	file, err := parser.ParseFile(token.NewFileSet(), "generated.go", source, 0)
	if err != nil {
		return "", 0, err
	}
	var expression ast.Expr
	ast.Inspect(file, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok || len(call.Args) != 3 {
			return true
		}
		selector, ok := call.Fun.(*ast.SelectorExpr)
		if ok && selector.Sel.Name == "New" {
			expression = call.Args[2]
			return false
		}
		return true
	})
	if expression == nil {
		return "", 0, fmt.Errorf("fontpkg.New bitmap expression not found")
	}
	return restoreStringExpression(expression)
}

func restoreStringExpression(expression ast.Expr) (string, int, error) {
	switch expression := expression.(type) {
	case *ast.BasicLit:
		if expression.Kind != token.STRING {
			return "", 0, fmt.Errorf("unexpected literal kind %s", expression.Kind)
		}
		value, err := strconv.Unquote(expression.Value)
		return value, 1, err
	case *ast.BinaryExpr:
		if expression.Op != token.ADD {
			return "", 0, fmt.Errorf("unexpected bitmap operator %s", expression.Op)
		}
		left, leftCount, err := restoreStringExpression(expression.X)
		if err != nil {
			return "", 0, err
		}
		right, rightCount, err := restoreStringExpression(expression.Y)
		if err != nil {
			return "", 0, err
		}
		return left + right, leftCount + rightCount, nil
	default:
		return "", 0, fmt.Errorf("unexpected bitmap expression %T", expression)
	}
}
